### ISSUE TITLE
Spacing in Ballot Categories

### ISSUE THREAD

**Issue by katjonzz** [WorldconVotingSystems/nomnom#43]
Some markdown for spacing is working in category descriptions, and some is not.

Where I just write paragraphs with space between then, that is working.

If I have a numbered list, that markdown isn't working, whether I use the numbered list markdown style in that markdown guide you gave us, or whether I use <br> at the end of lines exactly like you were.

See 'Professional Artist' detail for using numbered list like the markdown guide says
See 'Semiprozine' for use of <br>

Cassidy says I should note to you that it may be a CSS related issue, and that if it's style oriented we can delve into what styling to fix

**Comment by offbyone** [comment]
I'm afraid the issue is that you were "holding it wrong"

I made the following changes to the content and it worked:

1. You need a blank line after the paragraph text and before the lists start
2. You must use `.` as the period after numbers, not the Chinese punctuation that had been there.
3. For nested lists, I believe it is necessary to indent the nested list.

This content works: 

```
Notes: 

* A professional publication is one that meets at least one (1) of the following criteria:

    1. It provided at least a quarter of the income of any one person; or
    2. It was owned or published by any entity which provided at least a quarter of the income of any of its staff and/or owner.

 * 专业出版物必须至少符合下列两项准则之一：

    1. 它为任意一名人员提供了至少四分之一的个人收入；
    2. 拥有或出版它的实体为其中的任意员工和（或）所有者提供了至少四分之一的个人收入。
```
