### ISSUE TITLE
Minor contrast concern from Access

### ISSUE THREAD

**Issue by katjonzz** [WorldconVotingSystems/nomnom#91]
Meredith gave this feedback. Do you know what it means?

"Minor contrast concern - the text-dark class on the bg-light nav bar gave a contrast error in WAVE. Not sure about text-muted."

**Comment by offbyone** [comment]
If you want to tweak it, then the place that'd be done are here:

https://github.com/WorldconVotingSystems/nomnom/blob/main/glasgow2024/static/css/glasgow2024.css#L18-L20

The problem is that the text in the navbar (the words on the right in this image) are a bit muted. I don't think it's bad enough to be an issue, but the CSS there is where you change it.


![Image](https://github.com/WorldconVotingSystems/nomnom/assets/181693/2cab13c6-8423-4e34-bf09-b7f275a0d878)
